version: '3.3'

services:
  db:
    image: mysql
    container_name: ${MYSQL_HOST}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  nestjs:
    container_name: nestjs_api
    restart: always
    build: .
    volumes:
      - .:/var/www
      - ./src:/var/www/src
      - ./test:/var/www/test
    working_dir: /var/www/
    ports:
      - 3000:3000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    ports:
      - 8081:80

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWD}
    volumes:
      - ./data:/data
